# Generated by Django 5.2.7 on 2025-11-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeddingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="wedding_images/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("pre_wedding", "Pre-Wedding"),
                            ("haldi", "Haldi"),
                            ("mehndi", "Mehndi"),
                            ("sagan", "Sagan"),
                            ("rokha", "Rokha"),
                            ("wedding", "Wedding"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order", "-uploaded_at"],
            },
        ),
    ]
