# Generated by Django 5.2.7 on 2025-11-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_weddingmedia_delete_weddingimage"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WeddingMedia",
            new_name="WeddingImage",
        ),
    ]
