# Generated by Django 5.2.7 on 2025-12-09 08:12
import gallery.models
from django.db import migrations, models
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_rename_weddingmedia_weddingimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weddingimage",
            options={
                "ordering": ["category", "order", "-uploaded_at"],
                "verbose_name": "Wedding Media",
                "verbose_name_plural": "Wedding Media",
            },
        ),
        migrations.AddField(
            model_name="weddingimage",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Auto-generated smaller version of the image for fast loading",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="weddingimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Upload image files only",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="weddingimage",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Upload video files only",
                null=True,
                upload_to=gallery.models.wedding_video_upload_path,
            ),
        ),
    ]
