# Generated by Django 5.2.7 on 2025-12-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0004_alter_weddingimage_options_weddingimage_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weddingimage",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload image files only",
                null=True,
                upload_to="wedding_images/",
            ),
        ),
        migrations.AlterField(
            model_name="weddingimage",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Auto-generated smaller version of the image for fast loading",
                null=True,
                upload_to="thumbnails/",
            ),
        ),
    ]
