# Generated by Django 5.2.7 on 2025-12-29 13:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_weddingimage_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="weddingimage",
            name="thumbnail",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Auto-generated thumbnail",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
    ]
